In [12]:
import pandas as pd

In [13]:
# reading the CSV file
Report = pd.read_csv('C:/Users/dhris/data/anime.csv')

### Preparation and Cleaning

In [14]:
Report

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [3]:
Report.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [15]:
Report.shape  #Initial Shape

(12294, 7)

In [16]:
Report.columns

Index(['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members'], dtype='object')

In [17]:
type(Report)

pandas.core.frame.DataFrame

In [18]:
Report.dtypes

anime_id      int64
name         object
genre        object
type         object
episodes     object
rating      float64
members       int64
dtype: object

In [19]:
Report.isna().any()

anime_id    False
name        False
genre        True
type         True
episodes    False
rating       True
members     False
dtype: bool

In [20]:
Report.dropna(inplace=True)

In [21]:
Report

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [22]:
Report.shape #Shape after dropping NaN values

(12017, 7)

In [6]:
Report.loc[(Report["type"] == "TV"), ["name", "episodes", "rating"]]

                                                    name episodes  rating
1                       Fullmetal Alchemist: Brotherhood       64    9.26
2                                               Gintama°       51    9.25
3                                            Steins;Gate       24    9.17
4                                          Gintama&#039;       51    9.16
5      Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...       10    9.15
...                                                  ...      ...     ...
11104                          Wake Up, Girls! Shin Shou  Unknown     NaN
11106                             Yami Shibai 4th Season  Unknown     NaN
11107                                        Youjo Senki  Unknown     NaN
11110  Yuuki Yuuna wa Yuusha de Aru: Washio Sumi no Shou        6     NaN
11111       Yuuki Yuuna wa Yuusha de Aru: Yuusha no Shou        6     NaN

[3787 rows x 3 columns]

In [23]:
anime_df = Report[['name', 'genre', 'rating']]
anime_df

,name,genre,rating
0,Kimi no Na wa.,"Drama, Romance, School, Supernatural",9.37
1,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",9.26
2,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",9.25
3,Steins;Gate,"Sci-Fi, Thriller",9.17
4,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",9.16
...,...,...,...
12289,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,4.15
12290,Under World,Hentai,4.28
12291,Violence Gekiga David no Hoshi,Hentai,4.88
12292,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,4.98
12293,Yasuji no Pornorama: Yacchimae!!,Hentai,5.46

In [25]:
anime_df.isna().sum()

name        0
genre      62
rating    230
dtype: int64